### ISSUE TITLE
[Question] What you think about Nim and Vala

### ISSUE THREAD

**Issue by gavr123456789** [aeldemery/sinewave#1]
I saw you mention an example in nim, I really like both nim and vala(so far more vala due to its simplicity), I am interested in other people's opinions about these two languages.

**Comment by gavr123456789** [comment]
(Also, thanks for GTK 4 simple examples, community really need this)

**Comment by gavr123456789** [comment]
Oh, I just remembered that I already asked about D the same thing, hehe.

**Comment by aeldemery** [comment]
Thanks for asking. As I said before I am not really a programmer. Only on weekends I got a chance to play a little bit with programming. I started this sinewave example originally from Nim. I like it's pythonic syntax, but eventually I got irritated by some of it's limitations, for example forward declaration! I think this not acceptable in modern languages.
Speaking of Gtk4, I'm stuck with some issues that I could not clearly reason about. And lack of good documentation don't help either.
Perhaps you could help. The big hurdle for me is the new Gtk.Expression specially ClosureExpression.
If you have some ideas I would be happy to hear it from you.
Thanks.

**Comment by gavr123456789** [comment]
I haven't touched the GTK 4 at all yet. I've looked at your questions in the discourse, but I don't have any ideas yet.

**Comment by gavr123456789** [comment]
I also saw your question in IRC, I advise you to go there via Riot instead of IRC, so it will be more like a chat.

**Comment by aeldemery** [comment]
Thanks for the advice :)
